version: '3'

services:
  signoz:
    networks:
      - web
      - signoz-net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.signoz-frontend.rule=Host(\signoz.hmti.com.br\)'
      - 'traefik.http.routers.signoz-frontend.entrypoints=websecure'
      - 'traefik.http.routers.signoz-frontend.tls=true'
      - 'traefik.http.routers.signoz-frontend.tls.certresolver=lets-encrypt'
      - 'traefik.http.services.signoz-frontend.loadbalancer.server.port=8080'
      - 'traefik.docker.network=web'

  otel-collector:
    networks:
      - web
      - signoz-net

  clickhouse:
    networks:
      - web
      - signoz-net

networks:
  web:
    external: true
  signoz-net:
    external: true
