version: "3.8"

services:
  minhaapi:
    image: minhaapi:latest
    container_name: api-teste
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      # 1) Router HTTP: redireciona para HTTPS
      - "traefik.http.routers.api-http.rule=PathPrefix(`/dev/minhaapi`)"
      - "traefik.http.routers.api-http.entrypoints=web"
      - "traefik.http.routers.api-http.middlewares=redirect-dev-minhaapi"

      # 2) Router HTTPS: atende a requisição em TLS
      - "traefik.http.routers.api.rule=PathPrefix(`/dev/minhaapi`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt-prod"
      - "traefik.http.services.api.loadbalancer.server.port=7000"

      # 3) Middleware de redirecionamento HTTP → HTTPS
      - "traefik.http.middlewares.redirect-dev-minhaapi.redirectScheme.scheme=https"
      - "traefik.http.middlewares.redirect-dev-minhaapi.redirectScheme.permanent=true"

    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:7000"   # expõe sua aplicação .NET (interna escuta em 7000)
networks:
  traefik:
    external: true
