version: "3.8"

services:
  minhaapi:
    image: minhaapi:latest
    container_name: api-teste
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.hmti.com.br`)"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=lets-encrypt"
      - "traefik.http.services.app.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # OpenTelemetry Configuration
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz-otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=testecarga-api-dev
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=development,service.version=1.0.0
      # Enable OpenTelemetry Logs
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true

networks:
  web:
    external: true
