version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123
    volumes:
      - ../../shared/mongodb/data:/data/db
    networks:
      - dev_net

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - dev_net

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    networks:
      - dev_net

  minhaapi:
    image: minhaapi:latest
    container_name: api-teste
    ports:
      - "8080:80"
    networks:
      - dev_net

networks:
  dev_net:


volumes:
  portainer_data:
